import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import { Noto_Sans_JP } from "next/font/google"

const notoSansJP= Noto_Sans_JP({
  subsets:["latin"],
  weight:["400","500","700"]
})
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ja"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className={notoSansJP.className} >
        <div className="flex min-h-screen">
          <aside className="w-64 bg-white border-r border-slate-200">
            <Sidebar />
          </aside>
          <main className="flex-1 bg-white p-6 " >{children}</main>
        </div>
      </body>
    </html>
  );
}
